default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: dpg-cois0on79t8c738ma0r0-a.oregon-postgres.render.com
  username: luwis
  password: <%= ENV.fetch("PSQL_PASS") %>

development:
  <<: *default
  database: devDb

test:
  <<: *default
  database: testDb

production:
  <<: *default
  database: db
