default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV["PSQL_HOST"] || "localhost" %>
  username: <%= ENV["PSQL_USERNAME"] %>
  password: <%= ENV["PSQL_PASSWORD"] %>

development:
  <<: *default
  database: devDb

test:
  <<: *default
  database: testDb

production:
  <<: *default
  database: db
