default: &default
  adapter: postgresql
  url: <%= ENV["POSTGRES_URL"] %>
  pool: 5

development:
  <<: *default
  database: devDb

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  database: db
